---
engines:
 rubocop:
   enabled: true
   exclude_paths:
     - config/engines.yml
 duplication:
   enabled: false
 metrics:
   enabled: true
   exclude_paths:
     - config/engines.yml
 coverage:
   enabled: false
   exclude_paths:
     - config/engines.yml
